In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('Student_Performance.csv')

In [4]:
df.drop(columns=['Extracurricular Activities'],inplace=True)

In [31]:
class myLR:
    def __init__(self):
        self.coef_= None
        self.intercept_= None
        
    def fit(self,X_train, y_train):
        X_train=np.insert(X_train,0,1,axis=1)
        beta=np.linalg.inv(np.dot(X_train.T,X_train))@X_train.T@y_train
        self.intercept_=beta[0]
        self.coef_=beta[1:]
        # # print(beta)
        # print(self.intercept_)
        # print(self.coef_)

    def predict(self, X_test):
        return X_test@self.coef_ + self.intercept_
        

In [6]:
X=df.iloc[:,0:4].values
y=df.iloc[:,-1].values

In [7]:
X


array([[ 7, 99,  9,  1],
       [ 4, 82,  4,  2],
       [ 8, 51,  7,  2],
       ...,
       [ 6, 83,  8,  5],
       [ 9, 97,  7,  0],
       [ 7, 74,  8,  1]], dtype=int64)

In [8]:
y

array([91., 65., 45., ..., 74., 95., 64.])

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [32]:
lr=myLR()

In [33]:
lr.fit(X_train,y_train)

In [38]:
y_pred=lr.predict(X_test)

In [39]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [40]:
MAE=mean_absolute_error(y_test,y_pred)
MSE=mean_squared_error(y_test,y_pred)
RMSE=np.sqrt(mean_squared_error(y_test,y_pred))
R2=r2_score(y_test,y_pred)

In [41]:
print(f'MAE={MAE}\nMSE={MSE}\nRMSE={RMSE}\nR2={R2}')


MAE=1.6296726874197092
MSE=4.182254914593852
RMSE=2.045056213064534
R2=0.9887144552384186


In [42]:
lr.coef_

array([2.85289351, 1.01703572, 0.47331832, 0.19172629])

In [43]:
lr.intercept_

-33.60206732749241